config/routes.rb
Rails.application.routes.draw do

  resources :airlines
  resources :flights do
    resources :passengers
  end

  root 'flights#index'

end

app/models/airline.rb
class Airline < ActiveRecord::Base
  has_many :flights
end

app/models/arrival.rb
class Arrival < ActiveRecord::Base
  belongs_to :flight

  enum status: [:closed, :on_gate, :boarding, :took_off]
end

app/models/departure.rb
class Departure < ActiveRecord::Base
  belongs_to :flight

  enum status: [:closed, :on_gate, :boarding, :took_off]
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :airline
  has_many :passengers
  has_one :departure
  has_one :arrival

  accepts_nested_attributes_for :departure, :arrival
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :flight
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
  def index
    @airlines = Airline.all
  end

  def show
    @airline = Airline.find(params[:id])
  end

  def new
    @airline = Airline.new
  end

  def edit
    @airline = Airline.find(params[:id])
  end

  def create
    @airline = Airline.new(airline_params)

    if @airline.save
      redirect_to @airline
    else
      render 'new'
    end
  end

  def update
    @airline = Airline.update(airline_params)

    if @airline.updage
      redirect_to @airline
    else
      render 'edit'
    end
  end

  def destroy
    @airline = Airline.find(params[:id])
    @airline.destroy

    redirect_to airlines_path
  end

  private
  def airline_params
    params.require(:airline).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
  end

  def show
    @flight = Flight.find(params[:id])
  end

  def new
    @flight = Flight.new
    @flight.build_departure
    @flight.build_arrival
  end

  def edit
    @flight = Flight.find(params[:id])
  end

  def create
    @flight = Flight.new(flight_params)

    if @flight.save
      redirect_to @flight
    else
      render 'new'
    end
  end

  def update
    @flight = Flight.update(flight_params)

    if @flight.update
      redirect_to @flight
    else
      render 'edit'
    end
  end

  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy

    redirect_to flights_path
  end

  private
  def flight_params
    params.require(:flight).permit(:airline_id, :number, departure_attributes: [:date, :status, :flight_id], arrival_attributes: [:date, :status, :fligth_id])
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  def index
    @flight = Flight.find(params[:flight_id])
  end

  def new
    @passenger = Passenger.new
  end

  def show
    @flight = Flight.find(params[:flight_id])
    @passenger = @flight.passengers.find(params[:id])
  end

  def create
    @flight = Flight.find(params[:flight_id])
    @passenger = @flight.passengers.create(passenger_params)

    @passenger.save
    redirect_to flight_passenger_url(@flight, @passenger)
  end

  private
  def passenger_params
    params.require(:passenger).permit(:flight_id, :name, :passport)
  end
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/airlines/_form.html.erb
<%= form_for @airline do |f| %>
  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', airlines_path %>

app/views/airlines/edit.html.erb
<h1>Editing Airline</h1>

<%= render 'form' %>

app/views/airlines/index.html.erb
<h1>Listing Airlines</h1>
<p><%= link_to 'New Airline', new_airline_path %></p>

<table class="table">
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  <% @airlines.each do |airline| %>
    <tr>
      <td><%= airline.name %></td>
      <td><%= link_to 'Show', airline_path(airline) %></td>
      <td><%= link_to 'Edit', edit_airline_path(airline) %></td>
      <td><%= link_to 'Destroy', airline_path(airline),
              method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/airlines/new.html.erb
<h1>New Airline</h1>

<%= render 'form' %>

app/views/airlines/show.html.erb
<h1>Showing Airline</h1>

<p>
  <strong>Name:</strong>
  <%= @airline.name %>
</p>

<p><%= link_to 'Back', airlines_path %></p>

app/views/flights/_form.html.erb
<%= form_for @flight do |f| %> 
  <p>
    <%= f.label :number %>
    <%= f.number_field :number %>
  </p>

  <hr>  

  <h4>Departure:</h4>

  <%= f.fields_for :departure do |builder| %>
    <p>
      <%= builder.label :status %> <br>
      <%= builder.select :status, options_for_select(Departure.statuses.keys) %>
    </p>
    <p>
      <%= builder.label :date %> <br>
      <%= builder.datetime_select :date %>
    </p>
  <% end %>

  <hr>

  <h4>Arrival:</h4>

  <%= f.fields_for :arrival do |builder| %>
    <p>
      <%= builder.label :status %> <br>
      <%= builder.select :status, options_for_select(Arrival.statuses.keys) %>
    </p>
    <p>
      <%= builder.label :date %> <br>
      <%= builder.datetime_select :date %>
    </p>
  <% end %>

  <hr> 

<p>
  <%= f.submit %>
</p>

<% end %>

<%= link_to 'Back', flights_path %>

app/views/flights/edit.html.erb
<h1>Editing Flights</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<h1>Listing Flights</h1>
<p>
  <%= link_to 'New flight', new_flight_path %>
</p>

<% @flights.each do |flight| %>
<div class="panel panel-default">

  <div class="panel-heading">
    <h4><%= link_to flight_path(flight) do %>
      Flight Number <%= flight.number %> - <%= flight.airline.name %>
      <% end %> 
      <span>
        <%= link_to edit_flight_path(flight) do %>
        <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        <%= link_to flight_path(flight) , method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      </span>
    </h4>   
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="panel-heading"><h5>Departure</h5></div>
      <table class="table">
        <tr>
          <th>Date</th>
          <th>Status</th>
        </tr>
        <tr>
          <td><%= flight.departure.date %></td>
          <td><%= flight.departure.status %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-6">
      <div class="panel-heading"><h5>Arrival</h5></div>
      <table class="table">
        <tr>
          <th>Date</th>
          <th>Status</th>
        </tr>
        <tr>
          <td><%= flight.arrival.date %></td>
          <td><%= flight.arrival.status %></td>
        </tr>
      </table>
    </div>
  </div>  
</div>
<% end %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

app/views/flights/show.html.erb
<h1>Showing Flight</h1>

<p>
  <strong>Airline:</strong>
  <%= @flight.airline.name %>
</p>

<p>
  <strong>Flight Number:</strong>
  <%= @flight.number %>
</p>

<p>
  <strong>Departure Time:</strong>
  <%= @flight.departure.date %>
</p>

<p>
  <strong>Arrival Time:</strong>
  <%= @flight.arrival.date %>
</p>

<p>
  <%= link_to 'Show passengers', flight_passengers_path(@flight) %>
</p>

<p>
  <%= link_to 'Back', flights_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airport2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/passengers/index.html.erb
<h1>Showing Passengers</h1>

<p><%= link_to 'New passenger', new_flight_passenger_path %></p>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Passport</th>
  </tr>
  <% @flight.passengers.each do |passenger| %>
    <tr>
      <td><%= passenger.name %></td>
      <td><%= passenger.passport %></td>
    </tr>
  <% end %>  
</table>

<%= link_to 'Back', flight_path(@flight) %>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= form_for :passenger, url: flight_passengers_path do |f| %>
  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :passport %> <br>
    <%= f.number_field :passport %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>  

app/views/passengers/show.html.erb
<h1>Showing Passenger</h1>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>
<p>
  <strong>Passport:</strong>
  <%= @passenger.passport %>
</p>

<%= link_to 'Back', flight_passengers_path %>